/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC4906__factory } from "./IERC4906__factory";
export { IERC5267__factory } from "./IERC5267__factory";
