/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20Permit } from "./IERC20Permit";
export type { NFTDutchAuctionERC20Bids } from "./NFTDutchAuctionERC20Bids";
export type { NFTDutchAuctionERC20Bids_v2 } from "./NFTDutchAuctionERC20Bids_v2";
export type { RandomMusicNFT } from "./RandomMusicNFT";
export type { TempoToken } from "./TempoToken";
